import com.google.common.base.Strings;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println( Strings.padStart("123", 5, '0')); // "00123" を返却します

    }
}
