
import java.util.*;
import java.io.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

        Properties props = new Properties();
        props.put("mail.smtp.host", "proxy");
        Session session = Session.getInstance(props, null);
        try{
            Message msg = new MimeMessage(session);
            msg.setFrom(new InternetAddress("nomura@netssc.co.jp"));
            //InternetAddress[] address = {new InternetAddress("nomura@netssc.co.jp")};
            InternetAddress[] address = {new InternetAddress("nomum@docomo.ne.jp")};
            msg.setRecipients(Message.RecipientType.TO, address);
            msg.setSubject("JavaMail APIs Test");
            msg.setSentDate(new Date());
            msg.setText("test message");
      
            Transport.send(msg);
          }catch(MessagingException mex){
            System.out.println("¥n--Exception handling in msgsendsample.java");
            mex.printStackTrace();
          }
    }
}
