
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    //static Logger logger = LoggerFactory.getLogger(App.class);
    static Logger logger = LoggerFactory.getLogger("AA");

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        logger.debug("debug message");
        logger.trace("trace message");
        logger.info("info message");
        logger.warn("warn message");
        logger.error("error message");
        try{
            A.a();
        }catch (Exception e){
            logger.error("err" , e);
        }

    }

    static class A {
        public static void a(){
            B.b();
        }
    }
    static class B {
        public static void b(){
            String a=null;
            a.toString();
        }
    }
}
