/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by '正寿' at '17/05/06 6:34' with Gradle 2.9
 *
 * @author 正寿, @date 17/05/06 6:34
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
