
import config.AppConfigManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());

        AppConfigManager.init();
        System.out.println(AppConfigManager.getConfig().toString());

    }
}
