server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto : update
  datasource:
#    driverClass: org.hsqldb.jdbcDriver
#    url: jdbc:hsqldb:file:./db/testdb;shutdown=true
#    user: sa
    driverClassName: org.apache.derby.jdbc.EmbeddedDriver
    url: jdbc:derby:db-apache;create=true
    username: sa
    password: sa
